symbols = ['AFFLE', 'TEXINFRA', 'DOLPHIN', 'DVL', 'SYRMA', 'MOLDTECH', 'SAHYADRI', 'MUFIN', 'ZEEL', 'DATAMATICS',
           'HILTON', 'SALONA', 'ZODIACLOTH', 'LGHL', 'SMLT', 'CONCORDBIO', 'RBZJEWEL', 'TIL', 'LXCHEM', 'POLYPLEX',
           'VISAKAIND', 'EMMBI', 'MTARTECH', 'ALICON', 'BBOX', 'INNOVACAP', 'KIMS', 'NUVAMA', 'JYOTICNC', 'STOVEKRAFT',
           'BALAMINES', 'GOLDIAM', 'VINATIORGA', 'PARKHOTELS', 'SUKHJITS', 'UNIENTER', 'SASTASUNDR', 'LORDSCHLO',
           'GOCLCORP', 'GPTHEALTH', 'CAPITALSFB', 'MAXESTATES', 'PPAP', '3MINDIA', 'BANSWRAS', 'OAL', 'GRMOVER',
           'SHANKARA', 'SHAREINDIA', 'DTIL', 'KOTHARIPRO', 'WSTCSTPAPR', 'VIPIND', 'CANTABIL', 'DIACABS', 'ORIENTBELL',
           'MASTEK', 'AZAD', 'JSFB', 'TOUCHWOOD', 'CEATLTD', 'PATANJALI', 'BSL', 'FLAIR', 'SAKAR', 'APOLLOPIPE',
           'PRSMJOHNSN', 'SIGNPOST', 'CYBERTECH', 'SKMEGGPROD', 'JINDALPOLY', 'FOODSIN', 'SHREEPUSHK', 'TEMBO',
           'MEGASTAR', 'DELPHIFX', 'VENUSREM', 'BUTTERFLY', 'KANPRPLA', 'BHARATGEAR', 'PRIVISCL', 'SANDUMA',
           'HITECHCORP', 'MASFIN', 'RUPA', 'VERANDA', 'HONASA', 'BLUEJET', 'MANGALAM', 'IITL', 'IRMENERGY', 'CINELINE',
           'SREEL', 'RATNAVEER', 'SHALPAINTS', 'KANORICHEM', 'TATVA', 'BATAINDIA', 'ZFCVINDIA', 'MANAKSIA', 'AGI',
           'CHEMCON', 'JIOFIN', 'JSWINFRA', 'ZUARI', 'BARBEQUE', 'LYKALABS', 'SPANDANA', 'SIGNATURE', 'IVP',
           'UTTAMSUGAR', 'SSWL', 'GOCOLORS', 'GANESHBE', 'CSBBANK', 'OPTIEMUS', 'TBZ', 'MEDICAMEQ', 'DIAMINESQ',
           'NIFTYMEDIA', 'RUBYMILLS', 'GAEL', 'ORBTEXP', 'SINCLAIR', 'VAIBHAVGBL', 'MVGJL', 'HONDAPOWER', 'INDIACEM',
           'SPARC', 'DICIND', 'PODDARMENT', 'APTUS', 'MOTISONS', 'APCL', 'SAKSOFT', 'ALKYLAMINE', 'OCCL', 'GROBTEA',
           'INDIASHLTR', 'SAMHI', 'MUFTI', 'INDIAGLYCO', 'NELCO', 'NIPPOBATRY', 'LOVABLE', 'DELTACORP', 'MARATHON',
           'RAJRATAN', 'NEXT50', 'VALIANTLAB', 'BANDHANBNK', 'KRITI', 'AEROFLEX', 'ENTERO', 'HLEGLAS', 'GICHSGFIN',
           'SIYSIL', 'VENKEYS', 'GREENPANEL', 'MEDPLUS', 'EPL', 'BAYERCROP', 'MANORG', 'RGL', 'INOXINDIA', 'NDTV',
           'SUNTECK', 'BLISSGVS', 'DENORA', 'NUVOCO', 'CREDITACC', 'PRITI', 'GSLSU', 'ADANIENSOL', 'SICALLOG',
           'MOREALTY', 'NCLIND', 'KRYSTAL', 'PFOCUS', 'HIMATSEIDE', 'TARSONS', 'EIFFL', 'BAJAJELEC', 'KTKBANK',
           'SCHAND', 'BANKA', 'SURAJEST', 'JAGSNPHARM', 'MUTHOOTMF', 'EQUAL50ADD', 'EPACK', 'VALIANTORG', 'UDS',
           'VINYLINDIA', 'GSPL', 'KKCL', 'ROUTE', 'HINDWAREAP', 'PYRAMID', 'ZAGGLE', 'HATSUN', 'SESHAPAPER', 'LANDMARK',
           'FUSION', 'CERA', 'IREDA', 'TOTAL', 'RUCHIRA', 'UNIVPHOTO', 'TANLA', 'SRHHYPOLTD', 'ISFT', 'DABUR', 'PGHL',
           'IGL', 'RAMKY', 'JAYBARMARU', 'HERANBA', 'NATHBIOGEN', 'STYLAMIND', 'KNRCON', 'TMB', 'IKIO', 'SAURASHCEM',
           'AVADHSUGAR', 'SULA', 'JTLIND', 'UFLEX', 'PANACEABIO', 'PAYTM', 'GANDHAR', 'SOUTHWEST', 'ANDHRAPAP', 'REFEX',
           'ALKALI', 'HEALTHADD', 'HIL', 'ICRA', 'ARMANFIN', 'MIDQ50ADD', 'MAKEINDIA', 'SBCL', 'FOCUS', 'PONNIERODE',
           'TVSELECT', 'IFBAGRO', 'DEVIT', 'PAGEIND', 'BSOFT', 'PGHH', 'RAMCOCEM', 'KAMOPAINTS', 'YATHARTH',
           'HEXATRADEX', 'RELINFRA', 'NAZARA', 'BIRLACABLE', 'JKPAPER', 'IOLCP', 'JINDWORLD', 'TVSSCS', 'TATATECH',
           'KRBL', 'BERGEPAINT', 'TRIGYN', 'GLOBUSSPR', 'MPHASIS', 'STLTECH', 'NAVINIFTY', 'IIFL', 'BSHSL', 'NAHARCAP',
           'WHEELS', 'HEALTHIETF', 'APCOTEXIND', 'KANSAINER', 'UNIPARTS', 'AMBIKCO', 'DALMIASUG', 'ASHAPURMIN',
           'SHARDACROP', 'DIAMONDYD', 'INDOCO', 'LOWVOL', 'HEUBACHIND', 'DBOL', 'JUNIPER', 'AWL', 'HCLTECH',
           'LICMFGOLD', 'IDEAFORGE', 'VISHNU', 'INDUSINDBK', 'RUSHIL', 'NIFTY50ADD', 'MUKANDLTD', 'ACLGATI', 'APTECHT',
           'KABRAEXTRU', 'VSTL', 'COFORGE', 'GREAVESCOT', 'IBULHSGFIN', 'DREAMFOLKS', 'NIFTYETF', 'RISHABH', 'SFL',
           'AXISTECETF', 'ANGELONE', 'HGS', 'SOMANYCERA', 'M&MFIN', 'RELCHEMQ', 'EMSLIMITED', 'DAVANGERE', 'KALAMANDIR',
           'BORORENEW', 'RKSWAMY', 'PLATIND', 'CHEVIOT', 'TCIEXP', 'DALBHARAT', 'JGCHEM', 'CHEMPLASTS', 'HINDUNILVR',
           'BANKETF', 'ASIANPAINT', 'CYIENT', 'AGARIND', 'SATIA', 'RRKABEL', 'CRAFTSMAN', 'HIKAL', 'LTTS', 'HNDFDS',
           'BALUFORGE', 'LAMBODHARA', 'AVALON', 'MHLXMIRU', 'NIITLTD', 'GNA', 'PEL', 'KRSNAA', 'GHCL', 'BAJAJFINSV',
           'CCL', 'RSYSTEMS', 'SONATSOFTW', 'SPORTKING', 'PRECAM', 'ACI', 'BAJFINANCE', 'HDFCBANK', 'IPL', 'AKZOINDIA',
           'SIS', 'AMNPLST', 'BOROLTD', 'SBIETFIT', 'KITEX', 'ESABINDIA', 'ATFL', 'KERNEX', 'SIGMA', 'ASKAUTOLTD',
           'GSEC10IETF', 'MEDIASSIST', 'SONACOMS', 'EMAMIPAP', 'ORIENTELEC', 'PIIND', 'STARHEALTH', 'HOMEFIRST', 'ITC',
           'NIFTYBETF', 'CANFINHOME', 'NAVINFLUOR', 'NIFMID150', 'KAJARIACER', 'RPSGVENT', 'PVRINOX', 'YATRA', 'GLOBAL',
           'TITAN', 'DEVYANI', 'FEDFINA', 'LIQUIDETF', 'HDFCLIQUID', 'LIQUIDCASE', 'INFOBEAN', 'SBICARD', 'SYNGENE',
           'YASHO', 'SENSEXIETF', 'AUBANK', 'LIQUID1', 'RAJESHEXPO', 'FLUOROCHEM', 'LIQUIDADD', 'ADANIENT', 'EXICOM',
           'LIQUIDSBI', 'IDFC', 'KOTAKBANK', 'INSECTICID', 'LIQUID', 'UPL', 'LIQUIDIETF', 'LIQUIDBEES', 'PUNJABCHEM',
           'CELLO', 'ATGL', 'PVSL', 'SRM', 'TIPSFILMS', 'AETHER', 'MOLDTKPAC', 'SHREECEM', 'NIFITETF', 'DYNPRO', 'LINC',
           'EXPLEOSOL', 'INFY', 'JLHL', 'BLSE', 'NILKAMAL', 'HDFCLIFE', 'HAPPSTMNDS', 'BANARISUG', 'NAHARSPING', 'GSS',
           'INDIAMART', 'RAIN', 'RIIL', 'BALPHARMA', 'SRF', 'ADORWELD', 'LOYALTEX', 'DOMS', 'DEEPAKFERT', 'CENTURYPLY',
           'SPECIALITY', 'SHEMAROO', 'RAMAPHO', 'DPWIRES', 'SUPERHOUSE', 'HEIDELBERG', 'RHIM', 'DHAMPURSUG', 'BBTCL',
           'JUBLFOOD', 'LTIM', 'BHARATWIRE', 'KAKATCEM', 'TTKPRESTIG', 'ICEMAKE', 'NIITMTS', 'JKLAKSHMI', 'ASTERDM',
           'DHARMAJ', 'RELAXO', 'TOKYOPLAST', 'SUNCLAY', 'MAYURUNIQ', 'NAHARINDUS', 'JAYSREETEA', 'BAJAJHCARE',
           'PERSISTENT', 'GNFC', 'GOPAL', 'RPTECH', 'MAHAPEXLTD', 'TVSHLTD', 'AKSHARCHEM', 'SAPPHIRE', 'VPRPL',
           'BHAGERIA', 'PSPPROJECT', 'CLEAN', 'LAOPALA', 'MENONBE', 'ATUL', 'RSWM', 'UCAL', 'APOLSINHOT', 'HAPPYFORGE',
           'GULPOLY', 'BHARTIHEXA', 'GMMPFAUDLR', 'PDSL', 'NURECA', 'COASTCORP', 'AARTIDRUGS', 'EVEREADY', 'UNIDT',
           'XPROINDIA', 'ROSSARI', 'TATAELXSI', 'VRLLOG', 'GARFIBRES', 'INDIGOPNTS', 'CAMPUS', 'ANURAS', 'JOCIL',
           'SAGCEM', 'BALRAMCHIN', 'DIVGIITTS', 'DONEAR', 'SHREYAS', 'SANGAMIND', 'ONWARDTEC', 'KRISHANA', 'RBA',
           'FINOPB', 'SUMICHEM', 'PODDARHOUS', 'APEX', 'COSMOFIRST', 'ANDHRSUGAR', 'CONSOFINVT', 'MANGCHEFER',
           'JNKINDIA', 'METROBRAND', 'KUANTUM', 'KINGFA', 'BAJEL', 'REDTAPE', 'MUTHOOTCAP', 'PALREDTEC', 'NETWEB',
           'SHIVALIK', 'NAHARPOLY', 'AHLEAST', 'ASTEC', 'AUTOAXLES', 'LTFOODS', 'MANYAVAR', 'MONTECARLO', 'AIIL',
           'FINEORG', 'MBAPL', 'GALAXYSURF', 'SIRCA', 'MATRIMONY', 'POKARNA', 'AVROIND', 'REPL', 'SUNDRMFAST',
           'HARIOMPIPE',
           'TASTYBITE', 'KIRIINDUS', 'SRGHFL', 'SEMAC', 'GLOSTERLTD', 'SECMARK', 'ROLEXRINGS', 'ASIANHOTNR',
           'PRINCEPIPE']

s = ['CUMMINSIND',
     'ZEEL',
     'TRENT',
     'HAL',
     'PIIND',
     'TATACOMM',
     'TATAPOWER',
     'MFSL',
     'SBIN',
     'BANKBARODA',
     'ALKEM',
     'IOC',
     'BPCL',
     'OFSS',
     'CANBK',
     'POWERGRID',
     'CONCOR',
     'VOLTAS',
     'OBEROIRLTY',
     'BEL',
     'MCX',
     'NAUKRI',
     'COALINDIA',
     'PAGEIND',
     'HINDALCO',
     'ZYDUSLIFE',
     'PVRINOX',
     'TCS',
     'HCLTECH',
     'RELIANCE',
     'CUB',
     'LUPIN',
     'AUROPHARMA',
     'INDUSTOWER',
     'BAJAJ-AUTO',
     'GAIL',
     'ONGC',
     'APOLLOHOSP',
     'LICHSGFIN',
     'BOSCHLTD',
     'ACC',
     'BSOFT',
     'MPHASIS',
     'HINDPETRO',
     'DLF',
     'BHARTIARTL',
     'PNB',
     'NTPC',
     'NMDC',
     'HEROMOTOCO',
     'INDIGO',
     'COFORGE',
     'INDIAMART',
     'ESCORTS',
     'INDHOTEL',
     'SRF',
     'ABCAPITAL',
     'SUNPHARMA',
     'RECLTD',
     'LTTS',
     'DRREDDY',
     'MRF',
     'SBICARD',
     'BHARATFORG',
     'SUNTV',
     'HDFCAMC',
     'INFY',
     'HAVELLS',
     'BHEL',
     'NATIONALUM',
     'TORNTPHARM',
     'CROMPTON',
     'ICICIGI',
     'JUBLFOOD',
     'GUJGASLTD',
     'MCDOWELL-N',
     'JINDALSTEL',
     'PFC',
     'EXIDEIND',
     'BATAINDIA',
     'IEX',
     'TATASTEEL',
     'HINDUNILVR',
     'LTIM',
     'GMRINFRA',
     'NAVINFLUOR',
     'COROMANDEL',
     'PERSISTENT',
     'ASTRAL',
     'TITAN',
     'IPCALAB',
     'TECHM',
     'ADANIPORTS',
     'DABUR',
     'LAURUSLABS',
     'BANDHANBNK',
     'MARICO',
     'MGL',
     'IRCTC',
     'SIEMENS',
     'SBILIFE',
     'TATAMOTORS',
     'DIXON',
     'IDEA',
     'CIPLA',
     'INDIACEM',
     'ASHOKLEY',
     'AMBUJACEM',
     'DEEPAKNTR',
     'LT',
     'TVSMOTOR',
     'ABFRL',
     'DIVISLAB',
     'VEDL',
     'BAJAJFINSV',
     'BERGEPAINT',
     'WIPRO',
     'UBL',
     'POLYCAB',
     'FEDERALBNK',
     'L&TFH',
     'BIOCON',
     'BALKRISIND',
     'TATACHEM',
     'PETRONET',
     'M&MFIN',
     'ABBOTINDIA',
     'ADANIENT',
     'HDFCBANK',
     'GODREJCP',
     'ASIANPAINT',
     'RBLBANK',
     'M&M',
     'MARUTI',
     'JSWSTEEL',
     'ICICIPRULI',
     'ATUL',
     'COLPAL',
     'BAJFINANCE',
     'APOLLOTYRE',
     'MOTHERSON',
     'GRANULES',
     'RAMCOCEM',
     'IGL',
     'GRASIM',
     'IDFC',
     'ULTRACEMCO',
     'GLENMARK',
     'SYNGENE',
     'INDUSINDBK',
     'TATACONSUM',
     'HDFCLIFE',
     'HINDCOPPER',
     'SHREECEM',
     'SHRIRAMFIN',
     'CHOLAFIN',
     'GNFC',
     'PIDILITIND',
     'BALRAMCHIN',
     'IDFCFIRSTB',
     'DALBHARAT',
     'JKCEMENT',
     'ABB',
     'UPL',
     'SAIL',
     'ICICIBANK',
     'EICHERMOT',
     'NESTLEIND',
     'AXISBANK',
     'BRITANNIA',
     'GODREJPROP',
     'MANAPPURAM',
     'LALPATHLAB',
     'AUBANK',
     'KOTAKBANK',
     'PEL',
     'CHAMBLFERT',
     'CANFINHOME',
     'ITC',
     'MUTHOOTFIN',
     'AARTIIND',
     'DELTACORP',
     'METROPOLIS']

symbol200 = ['BDL',
             'CUMMINSIND',
             'ZEEL',
             'LICI',
             'TRENT',
             'OIL',
             'MANKIND',
             'HAL',
             'MAXHEALTH',
             'TORNTPOWER',
             'PIIND',
             'TATACOMM',
             'TATAPOWER',
             'MFSL',
             'SBIN',
             'BANKBARODA',
             'ALKEM',
             'IOC',
             'BPCL',
             'BANKINDIA',
             'CANBK',
             'KPITTECH',
             'JSWENERGY',
             'POWERGRID',
             'CONCOR',
             'VOLTAS',
             'OBEROIRLTY',
             'VBL',
             'UNIONBANK',
             'MSUMI',
             'BEL',
             'NAUKRI',
             'COALINDIA',
             'PAGEIND',
             'PATANJALI',
             'HINDALCO',
             'ZYDUSLIFE',
             'INDIANB',
             'MAZDOCK',
             'TCS',
             'HCLTECH',
             'ZOMATO',
             'RELIANCE',
             'LUPIN',
             'AUROPHARMA',
             'INDUSTOWER',
             'BAJAJ-AUTO',
             'GAIL',
             'APOLLOHOSP',
             'ONGC',
             'LICHSGFIN',
             'BOSCHLTD',
             'ACC',
             'BAJAJHLDNG',
             'MPHASIS',
             'YESBANK',
             'HINDPETRO',
             'DLF',
             'BHARTIARTL',
             'PNB',
             'NTPC',
             'NMDC',
             'HEROMOTOCO',
             'INDIGO',
             'DMART',
             'COFORGE',
             'INDHOTEL',
             'ESCORTS',
             'ABCAPITAL',
             'SRF',
             'SUNPHARMA',
             'RECLTD',
             'LTTS',
             'DRREDDY',
             'MRF',
             'SUNTV',
             'RVNL',
             'BHARATFORG',
             'SBICARD',
             'HDFCAMC',
             'INFY',
             'APLAPOLLO',
             'POLICYBZR',
             'HAVELLS',
             'BHEL',
             'TORNTPHARM',
             'CROMPTON',
             'ICICIGI',
             'JUBLFOOD',
             'GUJGASLTD',
             'IRFC',
             'MCDOWELL-N',
             'JINDALSTEL',
             'NHPC',
             'PFC',
             'BATAINDIA',
             'TATASTEEL',
             'HINDUNILVR',
             'LTIM',
             'NAVINFLUOR',
             'COROMANDEL',
             'PERSISTENT',
             'ASTRAL',
             'TITAN',
             'TECHM',
             'IPCALAB',
             'ADANIPORTS',
             'DABUR',
             'LAURUSLABS',
             'BANDHANBNK',
             'MARICO',
             'TATAELXSI',
             'IRCTC',
             'SIEMENS',
             'SBILIFE',
             'PGHH',
             'PRESTIGE',
             'TATAMOTORS',
             'DIXON',
             'FACT',
             'IDEA',
             'ADANIPOWER',
             'CIPLA',
             'ASHOKLEY',
             'TATAMTRDVR',
             'DEEPAKNTR',
             'AMBUJACEM',
             'LT',
             'TVSMOTOR',
             'DEVYANI',
             'ABFRL',
             'DIVISLAB',
             'VEDL',
             'BAJAJFINSV',
             'POONAWALLA',
             'BERGEPAINT',
             'WIPRO',
             'UBL',
             'POLYCAB',
             'FEDERALBNK',
             'L&TFH',
             'BIOCON',
             'BALKRISIND',
             'ATGL',
             'TATACHEM',
             'M&MFIN',
             'PETRONET',
             'CGPOWER',
             'ADANIENT',
             'HDFCBANK',
             'ASIANPAINT',
             'GODREJCP',
             'AWL',
             'M&M',
             'MARUTI',
             'JSWSTEEL',
             'ADANIENSOL',
             'ICICIPRULI',
             'COLPAL',
             'APOLLOTYRE',
             'BAJFINANCE',
             'FORTIS',
             'DELHIVERY',
             'MOTHERSON',
             'RAMCOCEM',
             'ADANIGREEN',
             'IGL',
             'GRASIM',
             'ULTRACEMCO',
             'GLAND',
             'SYNGENE',
             'INDUSINDBK',
             'TATACONSUM',
             'SHREECEM',
             'HDFCLIFE',
             'SHRIRAMFIN',
             'CHOLAFIN',
             'PIDILITIND',
             'IDFCFIRSTB',
             'ITC',
             'DALBHARAT',
             'LODHA',
             'ABB',
             'UPL',
             'TIINDIA',
             'SONACOMS',
             'SAIL',
             'NYKAA',
             'ICICIBANK',
             'EICHERMOT',
             'NESTLEIND',
             'AXISBANK',
             'FLUOROCHEM',
             'BRITANNIA',
             'GODREJPROP',
             'LALPATHLAB',
             'AUBANK',
             'KOTAKBANK',
             'PEL',
             'MUTHOOTFIN',
             'PAYTM']
small = ['NATIONALUM',	'CROMPTON',	'AEGISLOG',	'SAMMAANCAP',	'AVANTIFEED',	'BRIGADE',	'DEEPAKFERT',	'TECHNOE',	'KNRCON',	'CAPLIPOINT',	'JINDALSAW',	'RAJESHEXPO',	'BBTC',	'EQUITASBNK',	'RKFORGE',	'IFCI',	'QUESS',	'ACI',	'AMBER',	'ANANDRATHI',	'MASTEK',	'SWANENERGY',	'PRAJIND',	'GPIL',	'SHYAMMETL',	'PTCIL',	'CDSL',	'HEG',	'TRITURBINE',	'HFCL',	'CERA',	'NBCC',	'ALOKINDS',	'KANSAINER',	'KEC',	'GNFC',	'JUBLINGREA',	'TVSSCS',	'GRINFRA',	'DOMS',	'NSLNISP',	'GPPL',	'TBOTEK',	'ABSLAMC',	'LALPATHLAB',	'KFINTECH',	'EIHOTEL',	'ASTERDM',	'JBCHEPHARM',	'FSL',	'NETWEB',	'NETWORK18',	'KAYNES',	'JBMA',	'CLEAN',	'MAHSEAMLES',	'RRKABEL',	'CANFINHOME',	'CCL',	'UCOBANK',	'J&KBANK',	'BIRLACORPN',	'KPIL',	'HINDCOPPER',	'WELSPUNLIV',	'CRAFTSMAN',	'WELCORP',	'CASTROLIND',	'HSCL',	'JKTYRE',	'ZEEL',	'SBFC',	'GLENMARK',	'NATCOPHARM',	'LATENTVIEW',	'HBLPOWER',	'SCI',	'SOBHA',	'SONATSOFTW',	'ACE',	'CHEMPLASTS',	'360ONE',	'IEX',	'BLUESTARCO',	'KIRLOSENG',	'ISEC',	'CESC',	'TRIDENT',	'DATAPATTNS',	'TTML',	'CHAMBLFERT',	'INDGN',	'FINPIPE',	'CENTRALBK',	'ENGINERSIN',	'UJJIVANSFB',	'FINEORG',	'RBLBANK',	'MMTC',	'HOMEFIRST',	'REDINGTON',	'JKLAKSHMI',	'VIPIND',	'CEATLTD',	'OLECTRA',	'KARURVYSYA',	'IRCON',	'ERIS',	'SIGNATURE',	'TEJASNET',	'NH',	'JUSTDIAL',	'VINATIORGA',	'SUMICHEM',	'INDIACEM',	'RITES',	'ATUL',	'BATAINDIA',	'INDIAMART',	'METROPOLIS',	'VTL',	'NUVOCO',	'MAHLIFE',	'MANAPPURAM',	'GILLETTE',	'AAVAS',	'CUB',	'SUVENPHAR',	'JWL',	'CHALET',	'GODREJAGRO',	'GRAPHITE',	'GMDCLTD',	'LAURUSLABS',	'TITAGARH',	'PFIZER',	'SPARC',	'PVRINOX',	'ALKYLAMINE',	'RAMCOCEM',	'INTELLECT',	'PCBL',	'NAVINFLUOR',	'WHIRLPOOL',	'JMFINANCIL',	'APTUS',	'CGCL',	'ANGELONE',	'GAEL',	'CENTURYPLY',	'GRANULES',	'AARTIIND',	'JYOTICNC',	'IIFL',	'SYRMA',	'RHIM',	'INOXWIND',	'MOTILALOFS',	'INOXINDIA',	'KIMS',	'BIKAJI',	'MCX',	'RTNINDIA',	'NUVAMA',	'CREDITACC',	'GVT&D',	'GRSE',	'WESTLIFE',	'GODFRYPHLP',	'USHAMART',	'FINCABLES',	'LEMONTREE',	'MANYAVAR',	'NCC',	'RAILTEL',	'JUBLPHARMA',	'FIVESTAR',	'DEVYANI',	'GSFC',	'MAPMYINDIA',	'RCF',	'CHENNPETRO',	'BLS',	'SAPPHIRE',	'ABREL',	'JPPOWER',	'VGUARD',	'AFFLE',	'SANOFI',	'APLLTD',	'CAMPUS',	'CYIENT',	'ZENSARTECH',	'RATNAMANI',	'RENUKA',	'HAPPSTMNDS',	'POLYMED',	'VARROC',	'CAMS',	'MINDACORP',	'BSOFT',	'PNCINFRA',	'KSB',	'VIJAYA',	'TRIVENI',	'KAJARIACER',	'APARINDS',	'SWSOLAR',	'ARE&M',	'ANANTRAJ',	'EMCURE',	'EASEMYTRIP',	'RADICO',	'CIEINDIA',	'KIRLOSBROS',	'SCHNEIDER',	'PEL',	'CELLO',	'ROUTE',	'JYOTHYLAB',	'BALAMINES',	'CONCORDBIO',	'TANLA',	'SAREGAMA',	'ASAHIINDIA',	'RAYMOND',	'ELGIEQUIP',	'BEML',	'EIDPARRY',	'AADHARHFC',	'ITI',	'ELECON',	'DBREALTY',	'UTIAMC',	'GESHIP',	'BLUEDART',	'BALRAMCHIN',	'ECLERX',	'PNBHOUSING',	'RAINBOW',	'ASTRAZEN',	'CHOLAHLDNG',	'PPLPHARMA',	'GODIGIT',	'AKUMS',	'GSPL',	'BASF',	'NEWGEN',	'MGL',	'HONASA'
]
n = ['GODREJPROP','POWERGRID']
